version: "3.9"
services:
    webapp:
        build: .
        image: cepnisabann/mvcapp
        ports:
            - "8000:80"
        volumes:
            - Dockerfile
            - docker-compose.yml
            - entrypoint.sh
        depends_on:
            - videoscontext
    videoscontext:
        build: ./mssql_database
        image: cepnisabann/mvcdatabase
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "123456Aa@"
            SSQL_TCP_PORT: "1433"
            Trusted_Connection: "false"
            MultipleActiveResultSets: "true"
            TrustServerCertificate: "true"
            Pooling: "true"
            TZ: "UTC"
        ports:
            - "1433:1433"
        volumes:
            - ./opt/mssql/bin/sqlservr
            - ./mssql_database
volumes:
    database-data:
